### ISSUE TITLE
FormatException untarring archive published with Dart 2.17

### ISSUE THREAD

**Issue by todbachman-wf** [glesica/pkgraph#4]
Greetings pkgraph maintainer!

I've encountered the following exception when running `pkgraph:audit`:

```bash
Unhandled exception:
FormatException: EOF reached without finding string terminator
#0      InputStream.readString (package:archive/src/util/input_stream.dart:191:7)
#1      TarDecoder.decodeBuffer (package:archive/src/tar_decoder.dart:34:34)
#2      TarDecoder.decodeBytes (package:archive/src/tar_decoder.dart:12:12)
#3      LicenseAudit._drainQueue (package:pkgraph/src/license/license_audit.dart:130:47)
<asynchronous suspension>
#4      LicenseAudit.asMarkdown (package:pkgraph/src/license/license_audit.dart:66:5)
<asynchronous suspension>
#5      main (file:///root/.pub-cache/hosted/pub.dartlang.org/pkgraph-2.1.0+1/bin/audit.dart:43:17)
<asynchronous suspension>
Error producing PDF.
```

I added some logging to `lib/src/license/license_audit.dart` to figure out which package was causing the exception. Turned out it was [opentelemetry](https://pub.dev/packages/opentelemetry). The version `pkgraph` was downloading was `0.14.1`.  According to the maintainers of that package ( 😜 ) that release was published using Dart `2.17`. So we decided to try publishing a newer release of that package with Dart `2.13.4` to see if that would make a difference since we're running `pkgraph` on Dart `2.13.4`. When I ran `pkgraph` on a package that pulled in the `0.14.3` release of `opentelemetry` it worked just fine.

My suspicion is there might be a mismatch between the version of the archive package used by `pkgraph` and the version used by the Dart `2.17` `pub publish` command. But I could be wrong about that. It would be lovely if `pkgraph` could handle this mismatch more gracefully, though I'm not sure how easy it would be to make that work. 😬

**Comment by glesica** [comment]
I had forgotten ya'll were still using this!

The easiest thing might be to just upgrade some dependencies and then you can run it on Dart 2.17 and everything will (maybe?) be wonderful forever? Now that I've said that, I realized that the package isn't null-safe, so we'll see how much work that will be.

**Comment by glesica** [comment]
I pushed a branch called `upgrade-all-the-things`, is there a way you can try that out and see if it works with the original version of `opentelemetry`?

**Comment by todbachman-wf** [comment]
I'll report back shortly. Thanks for the quick turnaround @glesica !

**Comment by todbachman-wf** [comment]
That seems to have fixed it! I ran it with both the original opentelemetry release as well as the latest release and both worked just fine.

**Comment by todbachman-wf** [comment]
FWIW, it looks like at least one of the dependencies you upgraded requires Dart >=2.14. You might want to bump the SDK minimum in your pubspec.yaml to >=2.14 as well.

This is what I got when trying to globally activate pkgraph on Dart 2.13.4:

```bash
The current Dart SDK version is 2.13.4.

Because pkgraph depends on json_serializable >=6.0.0 which requires SDK version >=2.14.0 <3.0.0, version
  solving failed.
```

**Comment by glesica** [comment]
Updated. If you're satisfied, then, I'll merge that into master and then cut a release. I'm bumping the major to 3.0.0, FYI.

**Comment by glesica** [comment]
https://github.com/glesica/pkgraph/pull/5

**Comment by todbachman-wf** [comment]
I tested the branch already and it will work just fine for our use case. So merge and release whenever you are ready. Thanks again for the prompt fix!
